model_config:
  conf: 0.5 # Detection confidence threshold
  classes: [0, 8] # Class IDs to detect (e.g., 0 for person, 8 for boat)
  persist: True # Persist tracks across frames
  verbose: False # Disable verbose output
model: "yolov8n.pt"
